### PR TITLE
Added setup.py

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
@qstokkink this PR is ready and the setup.py seems to work fine 👍

**Comment by qstokkink** [comment]
@devos50 thanks!

**Pull request merged**
